file_name<- paste("C:/PyStuff/BioScripting/test/rescaledbase_allcoords.txt",sep="")
data<-read.table(file_name,col.names=c("coord1","coord2","coord3","coord4","coord5","coord6","coord7"))
plot_title<-paste("Coordinates Relative to Topology #1 Centre",sep=" ")
outfile_name<-paste("C:/PyStuff/BioScripting/test/quadrant_plots/all_topos.pdf",sep="")
pdf(outfile_name)
plot.default(data$coord1,data$coord2,main=plot_title,asp=1)
points(1,10,col=69,pch=15)
dev.off()

file_name<- paste("C:/PyStuff/BioScripting/test/rescaledbase_allcoords.txt",sep="")
data<-read.table(file_name,col.names=c("coord1","coord2","coord3","coord4","coord5","coord6","coord7"))
plot_title<-paste("Coordinates Relative to Topology #1 Centre",sep=" ")
outfile_png<-paste("C:/PyStuff/BioScripting/test/quadrant_plots/all_topos.png",sep="")
png(outfile_png,width=400,height=400)
plot.default(data$coord1,data$coord2,main=plot_title,asp=1)
points(1,10,col=69,pch=15)
dev.off()	